name: AI PR for Issues FROM REPO

on:
  issues:
    types: [opened]

jobs:
  ai-pr:
    uses: forproxyband/jira-issues-assigned-ai/.github/workflows/ai-issue-handler.yml@main
    with:
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      gh_pat: ${{ secrets.GH_PAT }}
      chromadb_host: ${{ secrets.CHROMADB_HOST }}
      chromadb_port: ${{ secrets.CHROMADB_PORT }}
      chromadb_token: ${{ secrets.CHROMADB_TOKEN }}
      chromadb_collection: openai-carp-travel

