name: Test Jira Webhook

on:
  repository_dispatch:
    types: [jira_webhook]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run with webhook data
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHROMADB_HOST: ${{ secrets.CHROMADB_HOST }}
          CHROMADB_PORT: ${{ secrets.CHROMADB_PORT }}
          CHROMADB_AUTH_TYPE: token
          CHROMADB_CREDENTIALS: ${{ secrets.CHROMADB_TOKEN }}
          CHROMADB_COLLECTION: openai-carp-travel
        run: |
          # Your script that processes the webhook
          node .github/scripts/src/process-webhook.js "${{ toJSON(github.event.client_payload) }}"
